# Generated by Django 6.0.3 on 2026-04-01 06:29

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to=notes.models.get_upload_path),
        ),
    ]
