# Generated by Django 6.0.3 on 2026-04-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
