# Generated by Django 6.0.3 on 2026-04-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_programme_subject_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_notes', to='notes.programme'),
        ),
    ]
